### ISSUE TITLE
file support?

### ISSUE THREAD

**Issue by Oltrex** [Moldoteck/MagicEraser#3]
can we get at least an ETA? compression destroys the images an this is currently the most accesible implementation of LaMa

**Comment by Moldoteck** [comment]
It is implemented in the code, but disabled, since my server can't handle such big images. If you want to run it, remove filtering by user id in a specific function. You would be able to send image files as original to your bot and get result with a powerful enough server. Making it work would require at least doubling my expenses on non gpu server on DO by using 8-16 gb of ram
